export const personalityGuideCopy = {
  de: {
    metaTitle: "Big-Five-Kompass",
    kicker: "Persönlichkeits-Kompass",
    title: "Eine klare Frage. Eine kurze, persönliche Antwort.",
    intro: "Nutze dein Big-Five-Profil als Perspektive auf Arbeit, Beziehungen und Alltag – knapp, konkret und ohne Schubladendenken.",
    profileTitle: "Dein Profil",
    profileFromTest: "Werte aus deinem letzten Test übernommen",
    profileManual: "Neutrale Startwerte – frei anpassbar",
    resetProfile: "Auf Mitte setzen",
    questionLabel: "Was beschäftigt dich?",
    questionPlaceholder: "Zum Beispiel: Wie kann ich Entscheidungen treffen, ohne alles zu zerdenken?",
    questionHint: "10 bis 500 Zeichen",
    suggestionsLabel: "Typische Fragen",
    submit: "Kurzantwort erhalten",
    submitting: "Antwort wird verdichtet …",
    answerKicker: "Kurzantwort",
    answerTitle: "Das Wichtigste zuerst",
    insightsTitle: "Drei praktische Hinweise",
    privacy: "TraitBridge speichert diese Frage und Antwort nicht. Die Anfrage wird zur Verarbeitung an OpenAI übertragen und kann dort gemäß den API-Datenrichtlinien vorübergehend zur Missbrauchsprävention aufbewahrt werden.",
    privacyLink: "OpenAI-Datenrichtlinien",
    errors: {
      invalid_request: "Bitte gib eine Frage mit 10 bis 500 Zeichen und gültige Profilwerte ein.",
      rate_limited: "Du hast gerade mehrere Fragen gestellt. Bitte warte etwa 15 Minuten.",
      configuration_error: "Das KI-Tool ist noch nicht vollständig eingerichtet.",
      provider_error: "Die KI-Antwort ist momentan nicht erreichbar. Bitte versuche es später erneut.",
      invalid_response: "Die Antwort hatte ein unerwartetes Format. Bitte versuche es erneut.",
      generic: "Die Anfrage konnte nicht verarbeitet werden.",
    },
    traits: {
      O: { label: "Offenheit", low: "praktisch", high: "entdeckend" },
      C: { label: "Gewissenhaftigkeit", low: "flexibel", high: "strukturiert" },
      E: { label: "Extraversion", low: "zurückhaltend", high: "kontaktorientiert" },
      A: { label: "Verträglichkeit", low: "direkt", high: "kooperativ" },
      N: { label: "Emotionale Empfindlichkeit", low: "robust", high: "sensibel" },
    },
    suggestions: [
      "Wie finde ich eine Arbeitsweise, die wirklich zu mir passt?",
      "Wie spreche ich Konflikte an, ohne mich zu verbiegen?",
      "Wie kann ich Entscheidungen treffen, ohne alles zu zerdenken?",
      "Was hilft mir, wenn Stress und Reize zu viel werden?",
      "Wie kommuniziere ich meine Bedürfnisse klarer?",
      "Welche kleine Gewohnheit würde meine Entwicklung unterstützen?",
    ],
  },
  en: {
    metaTitle: "Big Five Compass",
    kicker: "Personality Compass",
    title: "One clear question. One short, personal answer.",
    intro: "Use your Big Five profile as a perspective on work, relationships, and everyday life – concise, practical, and without putting you in a box.",
    profileTitle: "Your profile",
    profileFromTest: "Values loaded from your latest test",
    profileManual: "Neutral starting values – freely adjustable",
    resetProfile: "Reset to middle",
    questionLabel: "What is on your mind?",
    questionPlaceholder: "For example: How can I make decisions without overthinking everything?",
    questionHint: "10 to 500 characters",
    suggestionsLabel: "Typical questions",
    submit: "Get short answer",
    submitting: "Condensing your answer …",
    answerKicker: "Short answer",
    answerTitle: "The main point",
    insightsTitle: "Three practical pointers",
    privacy: "TraitBridge does not store this question or answer. The request is sent to OpenAI for processing and may be temporarily retained there for abuse prevention under its API data policies.",
    privacyLink: "OpenAI data policies",
    errors: {
      invalid_request: "Enter a question of 10 to 500 characters and valid profile values.",
      rate_limited: "You have asked several questions recently. Please wait about 15 minutes.",
      configuration_error: "The AI tool has not been fully configured yet.",
      provider_error: "The AI response is currently unavailable. Please try again later.",
      invalid_response: "The answer had an unexpected format. Please try again.",
      generic: "The request could not be processed.",
    },
    traits: {
      O: { label: "Openness", low: "practical", high: "explorative" },
      C: { label: "Conscientiousness", low: "flexible", high: "structured" },
      E: { label: "Extraversion", low: "reserved", high: "outgoing" },
      A: { label: "Agreeableness", low: "direct", high: "cooperative" },
      N: { label: "Emotional Sensitivity", low: "steady", high: "sensitive" },
    },
    suggestions: [
      "How can I find a way of working that genuinely suits me?",
      "How can I address conflict without pretending to be someone else?",
      "How can I make decisions without overthinking everything?",
      "What can help when stress and stimulation become too much?",
      "How can I communicate my needs more clearly?",
      "Which small habit could support my personal growth?",
    ],
  },
} as const;
